name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Get release version
        id: get_version
        uses: maltoze/get-version-action@v1

      # Makes updates to the manifest.json, replacing various properties like the
      # version and debug enabled status.
      - name: Update package manifest
        uses: restackio/update-json-file-action@2.1
        with:
          file: com.neil-enns.trackaudio.sdPlugin/manifest.json
          # Setting Nodejs.Debug to disabled is a bit of a hack to disable debugging in the release builds.
          # It isn't officially supported. It winds up getting passed as a command line argument to node.js
          # and seems to just be ignored, which works well enough.
          fields: '{"Version": "${{ steps.get_version.outputs.version-without-v }}.0", "Nodejs.Debug": "disabled"}'

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Pack
        run: npm run pack

      - name: Upload plugin
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.streamDeckPlugin
