name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Get release version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Update package version
        uses: restackio/update-json-file-action@2.1
        with:
          file: com.neil-enns.trackaudio.sdPlugin/manifest.json
          fields: '{"Version": "${{ steps.get_version.outputs.version-without-v }}.0"}'

      - name: Build
        run: npm run build

      - name: Pack
        run: npm run pack

      - name: Upload plugin
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.streamDeckPlugin
